import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
    title: 'Create Authnp',
    description: 'Generated by create next app',
  }
  

const AuthLayout = ({children}:{children:React.ReactNode}) => {
  return (
    <main className='h-full flex justify-center items-center'>{children}</main>
  )
}

export default AuthLayout